name: CI-TEST

on:
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
    - uses: actions/checkout@v2
    - name: Deploy with rsync
      # run: rsync -avz ./static/ exsania@69.16.202.91:/home/exsania/shahbaz/test-deploy
      run: rsync -avz ./static/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/exsania/shahbaz/test-deploy
      